name: Build Kivy APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"

    - name: Install Linux dependencies
      run: |
        sudo dpkg --add-architecture i386
        sudo apt update
        sudo apt install -y \
          build-essential \
          git \
          zip \
          unzip \
          openjdk-17-jdk \
          python3-pip \
          python3-setuptools \
          python3-wheel \
          python3-virtualenv \
          libssl-dev \
          libffi-dev \
          libncursesw5 \
          libncursesw5:i386

        pip install --upgrade pip
        pip install cython buildozer

    - name: Install Android SDK + cmdline-tools
      run: |
        mkdir -p $HOME/android-sdk/cmdline-tools/latest
        cd $HOME/android-sdk/

        wget https://dl.google.com/android/repository/commandlinetools-linux-11076708_latest.zip -O tools.zip
        unzip tools.zip
        mv cmdline-tools/* cmdline-tools/latest/
        rm tools.zip

        yes | $HOME/android-sdk/cmdline-tools/latest/bin/sdkmanager --licenses
        $HOME/android-sdk/cmdline-tools/latest/bin/sdkmanager "platform-tools" "build-tools;33.0.2" "platforms;android-33"

    - name: Set ENV paths
      run: |
        echo "export ANDROIDSDK=$HOME/android-sdk" >> $GITHUB_ENV
        echo "export ANDROIDNDK=$HOME/.buildozer/android/platform/android-ndk-r25b" >> $GITHUB_ENV
        echo "export PATH=$PATH:$HOME/android-sdk/platform-tools:$HOME/android-sdk/cmdline-tools/latest/bin" >> $GITHUB_ENV

    - name: Build APK with Buildozer
      run: |
        buildozer android debug

    - name: Upload APK artifact
      uses: actions/upload-artifact@v4
      with:
        name: safespot-apk
        path: bin/*.apk
